### PR TITLE
Feat/mohsen/add plg pool

### PR DESCRIPTION
**Pull request by mohsenParvar**

### CODE REVIEW

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Review by jomarip — APPROVED** [review]
Tested the changes. Seemed to work okay to me. Voting distribution will happen tomorrow as well. So updating of allocations will be viewable.

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-add_plg_pool.dev-app.axial.exchange

**Review by saito-sv — APPROVED** [review]

**Pull request merged**
