### PR TITLE
token approval helper

### PR DESCRIPTION
**Pull request by mohsenParvar**
* added helper for token approval, this helpers will receive a list of token, one of them will check if all are approved, the other one will check and try to approve, they internally handle the state of the app too, so we will not have to worry about the approval modal and logic

### CODE REVIEW

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-tokeVerifierModal.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-feat-mohsen-tokeVerifierModal.dev-app.axial.exchange

**Review by Sanjeev1308 — APPROVED** [review]
LGTM

**Review by saito-sv — APPROVED** [review]
LGTM

**Pull request merged**
