### PR TITLE
updated withdraw steps in TransactionSteps component

### PR DESCRIPTION
**Pull request by prodvdc**

### CODE REVIEW

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-david-tx-step-update.dev-app.axial.exchange

**Comment by ghost** [comment]
This PR shouldn't be to remove the tokens at the transaction steps?

image
It's still showing for me, tested on the live deployment and locally.

**Comment by prodvdc** [comment]
> This PR shouldn't be to remove the tokens at the transaction steps?
> 
> image It's still showing for me, tested on the live deployment and locally.

@Jonasslv 
I removed it(token symbol) only on withdrawal flow. I will remove the symbol on deposit flow too.

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-david-tx-step-update.dev-app.axial.exchange

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
