### PR TITLE
Solve Flickering

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-jonas-solve-flickering.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-jonas-solve-flickering.dev-app.axial.exchange

**Review by prodvdc — APPROVED** [review]
On top of "Deposit" button, there is 0

**Review by prodvdc — CHANGES_REQUESTED** [review]
image

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-jonas-solve-flickering.dev-app.axial.exchange

**Review by prodvdc — APPROVED** [review]
LGTM

**Pull request merged**
