### PR TITLE
added "compound with snowball" button to deposit only if AVAX-AXIAL pool

### PR DESCRIPTION
**Pull request by JoshuaLelon**
Added a "compound with snowball" button that links to snowball app (Snowball → Compound & Earn) only for the AVAX-AXIAL pool.

Before:
image

After:
image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201356688521658

### CODE REVIEW

**Comment by ghost** [comment]
Please when forking the repo to do a task, make a branch on the repo itself, it makes easier to test the changes.

**Comment by ghost** [comment]
We can add the "compound with snowball" button for all pools now instead of only JLP, since we have strategies for all of it

**Comment by JoshuaLelon** [comment]
> 

As in on the snowball repo itself, not my forked version, right?

**Comment by JoshuaLelon** [comment]
> We can add the "compound with snowball" button for all pools now instead of only JLP, since we have strategies for all of it

Ok, I will make that change

**Review by ghost — APPROVED** [review]
LGTM

**Pull request merged**
