### PR TITLE
Swap token modal design

### PR DESCRIPTION
**Pull request by Sanjeev1308**
To Test:
1. Please clicks on the token dropdown in swap page
2. Will open toke search modal, please compare with figma design https://www.figma.com/file/aGzcHpHztkm9Z48CB1X30S/Axial-Assets?node-id=1963%3A48102

Asana ticket: https://app.asana.com/0/1201433089668827/1202064151842521

### CODE REVIEW

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-sanjeev-swap-modal-design.dev-app.axial.exchange

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-sanjeev-swap-modal-design.dev-app.axial.exchange

**Comment by saito-sv** [comment]
Screen Shot 2022-04-05 at 10 01 00 AM
@Sanjeev1308  color on the scroll bar still does not match the designs

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-sanjeev-swap-modal-design.dev-app.axial.exchange

**Comment by Sanjeev1308** [comment]
> Screen Shot 2022-04-05 at 10 01 00 AM
> 
> @Sanjeev1308 color on the scroll bar still does not match the designs

Currently primary colour is this, that's why it is showing green, if I changed it to current design then will change to overall app.
Do I need to change?

**Comment by saito-sv** [comment]
This PR is automatically being deployed to https://preview-task-sanjeev-swap-modal-design.dev-app.axial.exchange

**Review by saito-sv — APPROVED** [review]
LGTM

**Pull request merged**
